plugins {
   id 'java'
   id 'application'
   id 'checkstyle'
   id 'org.ajoberstar.git-publish' version '4.2.0'
}

repositories {
    mavenCentral()
}


java {
    sourceCompatibility = JavaVersion.toVersion(17)
    targetCompatibility = JavaVersion.toVersion(17)
}

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter:5.7.0'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testImplementation 'org.hamcrest:hamcrest-library:2.2'
}

tasks.withType(Test) {
    useJUnitPlatform()
    ignoreFailures = true
    testLogging {
        events "passed", "skipped", "failed"
        }
}

checkstyle {
    toolVersion = '10.12.5'
    ignoreFailures = true
}

application { //Allows  ./gradlew run --args=path-to-test-data
    mainClass = 'edu.odu.cs.MostCommonWords'
}

tasks.register('reports') {
    dependsOn 'build'
    dependsOn 'javadoc'
    dependsOn 'checkstyleMain'

    doLast {
        copy {
            from 'src/main/html'
            into 'build/reports/'
        }

        copy {
            from 'build/docs/'
            into 'build/reports/'
        }

        copy {
            from 'build/reports/checkstyle/main.html'
            into 'build/reports/'
        }
    }
}

gitPublish {
    repoUri = 'git@github.com:ODU-CS351-F26/CS351--ciAsst--ryanmf2.git'

    branch = 'gh-pages'

    contents {
        from 'build/reports'
    }
}

gitPublishCopy.dependsOn 'reports'

tasks.register('deployReports') {
    dependsOn 'gitPublishPush'
}